nodeLinker: node-modules

# Use global (~/.yarnrc.yml) yarn config to prevent the need of committing the npmAuthToken here.
# Global and project configs are NOT merged (https://github.com/yarnpkg/berry/issues/1319), the reason why the config below is moved to the global.
# npmScopes:
#   'advantitge':
#     npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
